### PR TITLE
Refactoring + Error Redirects

### PR DESCRIPTION
**Pull request by qvalentin**

### CODE REVIEW

**Comment by qvalentin** [comment]
TODO:

[] query params for download
[] message is missing :(

**Comment by qvalentin** [comment]
Everything should be working. Code could be prettier but otherwise we can merge it.

**Review by open-schnick — APPROVED** [review]
nice job

**Comment by open-schnick** [comment]
Do you want to implement the query param `redirectOnError` in this branch or in a future one?

**Comment by qvalentin** [comment]
> Do you want to implement the query param `redirectOnError` in this branch or in a future one?

No need to hurry, as this need to wait for the frontend changes to be merged.

**Pull request merged**
